"""restart

Revision ID: 070ecbbcf964
Revises: cc36e0c4affe
Create Date: 2025-02-02 21:28:50.790565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '070ecbbcf964'
down_revision = 'cc36e0c4affe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_index('code')

    op.drop_table('coupon')
    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.drop_constraint('resume_certifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('certification_path')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('about_me')

    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certification_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('resume_certifications_ibfk_1', 'logins', ['user_id'], ['id'])

    op.create_table('coupon',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('faculty_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('year', mysql.VARCHAR(length=4), nullable=False),
    sa.Column('college_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], name='coupon_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.create_index('code', ['code'], unique=True)

    # ### end Alembic commands ###
