"""Rhhi

Revision ID: 12e8747af2c4
Revises: 4ce4f06aa47b
Create Date: 2025-02-02 22:31:59.843576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e8747af2c4'
down_revision = '4ce4f06aa47b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('college_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('college_name')

    # ### end Alembic commands ###
