"""migration 15

Revision ID: 185c80dd0445
Revises: 8b7dd38d30d9
Create Date: 2025-01-15 01:48:17.681805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '185c80dd0445'
down_revision = '8b7dd38d30d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.alter_column('message',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('communications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'logins', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'logins', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('communications_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.alter_column('message',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
