"""couponuser createdAt

Revision ID: 1db10a42d43c
Revises: 665d6f491379
Create Date: 2025-04-17 22:30:28.588279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1db10a42d43c'
down_revision = '665d6f491379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couponuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('couponuser', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
