"""thifs

Revision ID: 22594118131b
Revises: 697778600b33
Create Date: 2025-04-01 02:40:07.230544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22594118131b'
down_revision = '697778600b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_applied', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_status_changed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('interview_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['job_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_column('feedback')
        batch_op.drop_column('interview_date')
        batch_op.drop_column('date_status_changed')
        batch_op.drop_column('date_applied')

    # ### end Alembic commands ###
