"""tskkskkllak.

Revision ID: 281e13474692
Revises: b2892ddbc5a5
Create Date: 2025-04-01 03:22:47.636937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '281e13474692'
down_revision = 'b2892ddbc5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_column('feedback')
        batch_op.drop_column('date_status_changed')
        batch_op.drop_column('interview_date')
        batch_op.drop_column('date_applied')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_applied', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('interview_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_status_changed', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
