"""Rppi

Revision ID: 4ce4f06aa47b
Revises: 
Create Date: 2025-02-02 22:24:30.830614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ce4f06aa47b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_index('code')

    op.drop_table('coupon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('faculty_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('year', mysql.VARCHAR(length=4), nullable=False),
    sa.Column('college_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['college.id'], name='coupon_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.create_index('code', ['code'], unique=True)

    # ### end Alembic commands ###
