"""migration 5

Revision ID: 4e1d81d20f80
Revises: 
Create Date: 2025-01-12 17:00:31.528236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e1d81d20f80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_applications')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('skills', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('certifications', sa.Text(), nullable=True))
        batch_op.alter_column('deadline',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('deadline',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('certifications')
        batch_op.drop_column('skills')
        batch_op.drop_column('job_id')

    op.create_table('job_applications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('resume_path', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='job_applications_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='job_applications_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
