"""Added Resume table to store user resumes and certifications

Revision ID: 54524043101d
Revises: 
Create Date: 2024-12-31 13:57:48.730220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54524043101d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_path', sa.String(length=255), nullable=False),
    sa.Column('certification_path', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('resumes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('resume_filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('certification_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('upload_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('resume_certifications')
    # ### end Alembic commands ###
