"""Inition

Revision ID: 55ded17a0f1d
Revises: 8fa058501bcd
Create Date: 2025-01-26 20:31:51.268352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55ded17a0f1d'
down_revision = '8fa058501bcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certification_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.Boolean(), nullable=True))
        batch_op.drop_column('certification_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certification_path', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('verification_status')
        batch_op.drop_column('certification_name')

    # ### end Alembic commands ###
