"""Ri

Revision ID: 564c3e59ca50
Revises: ba9299ef29f6
Create Date: 2025-02-02 19:19:50.482305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564c3e59ca50'
down_revision = 'ba9299ef29f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_constraint('certifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.drop_constraint('resume_certifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('resume_certifications_ibfk_1', 'logins', ['user_id'], ['id'])

    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('certifications_ibfk_1', 'logins', ['user_id'], ['id'])

    # ### end Alembic commands ###
