"""Job table fields

Revision ID: 57375bab5c52
Revises: 697778600b33
Create Date: 2025-03-31 10:48:01.929828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57375bab5c52'
down_revision = '697778600b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('salary',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('salary',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
