"""Initon

Revision ID: 57e5f42df253
Revises: 55ded17a0f1d
Create Date: 2025-01-26 20:50:24.640326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57e5f42df253'
down_revision = '55ded17a0f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.drop_column('certification_name')
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('certification_name', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
