"""Added Resume table to store user resumes and certifications

Revision ID: 59cd6c602d70
Revises: d0477b40ad71
Create Date: 2024-12-31 14:06:35.079898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59cd6c602d70'
down_revision = 'd0477b40ad71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_certifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_certifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('resume_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('certification_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
