"""Reinitializing migrations

Revision ID: 5c74597e6e9c
Revises: 
Create Date: 2025-02-02 15:31:57.462750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c74597e6e9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_cert_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'resume_certifications', ['resume_cert_id'], ['id'])

    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_status', sa.Boolean(), nullable=False))
        batch_op.drop_column('read')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_status', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('notifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['user_id'], ['login_id'])
        batch_op.drop_column('read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notifications_ibfk_1', 'logins', ['user_id'], ['id'])
        batch_op.drop_column('hidden')
        batch_op.drop_column('read_status')

    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('read_status')

    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resume_cert_id')

    # ### end Alembic commands ###
