"""Years of exp in job table

Revision ID: 5d40f8c38505
Revises: 7ed0408e1e0d
Create Date: 2025-02-24 08:00:34.640616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d40f8c38505'
down_revision = '7ed0408e1e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('years_of_exp', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('years_of_exp')

    # ### end Alembic commands ###
