"""helloworld

Revision ID: 5e956132a1b9
Revises: 665d6f491379
Create Date: 2025-04-17 16:53:32.397348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e956132a1b9'
down_revision = '665d6f491379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_applied', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('status_updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('salary',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('salary',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_column('status_updated_at')
        batch_op.drop_column('date_applied')

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
