"""migration 24

Revision ID: 6204eff57efa
Revises: 5bdd8d1e4d3b
Create Date: 2025-01-26 23:39:35.875170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6204eff57efa'
down_revision = '5bdd8d1e4d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['login_id'])
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['login_id'])
        batch_op.drop_column('read')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_status', sa.Boolean(), nullable=False))
        batch_op.drop_constraint('notifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['user_id'], ['id'])
        batch_op.drop_column('read')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notifications_ibfk_1', 'logins', ['user_id'], ['id'])
        batch_op.drop_column('read_status')

    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
