"""coupon

Revision ID: 665d6f491379
Revises: a8e0a1e1c131
Create Date: 2025-04-17 11:09:33.775870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665d6f491379'
down_revision = 'a8e0a1e1c131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
