"""Industry Type Field

Revision ID: 697778600b33
Revises: a85552b84ad0
Create Date: 2025-03-30 22:18:12.931593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697778600b33'
down_revision = 'a85552b84ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('industry')

    # ### end Alembic commands ###
