"""tkkkkkk.

Revision ID: 778d7789cd7d
Revises: 281e13474692
Create Date: 2025-04-01 03:25:15.682687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778d7789cd7d'
down_revision = '281e13474692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_applied', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('status_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_column('status_updated_at')
        batch_op.drop_column('date_applied')

    # ### end Alembic commands ###
