"""Job Application Timestamps

Revision ID: 7be6bdb4f345
Revises: 778d7789cd7d
Create Date: 2025-04-02 05:40:20.206028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be6bdb4f345'
down_revision = '778d7789cd7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_applied', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('status_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_column('status_updated_at')
        batch_op.drop_column('date_applied')

    # ### end Alembic commands ###
