"""Inon

Revision ID: 7c0e5aaf31ad
Revises: 57e5f42df253
Create Date: 2025-01-26 23:45:18.752754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c0e5aaf31ad'
down_revision = '57e5f42df253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_constraint('communications_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('communications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['login_id'])
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['login_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('communications_ibfk_1', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('communications_ibfk_2', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
