"""Notification extra fields

Revision ID: 7ed0408e1e0d
Revises: 34c6bad72895
Create Date: 2025-02-23 12:11:39.756221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed0408e1e0d'
down_revision = '34c6bad72895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=False))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('notifications_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['login_id'])
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['login_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notifications_user_id_fkey', 'companies', ['user_id'], ['login_id'])
        batch_op.drop_column('company_id')

    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
