"""abcd

Revision ID: 8962e59ecda2
Revises: 
Create Date: 2025-02-02 19:24:32.890196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8962e59ecda2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_constraint('certifications_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('certifications_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('resume_cert_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_cert_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('certifications_ibfk_2', 'logins', ['user_id'], ['id'])
        batch_op.create_foreign_key('certifications_ibfk_1', 'resume_certifications', ['resume_cert_id'], ['id'])

    # ### end Alembic commands ###
