"""e3

Revision ID: 8fa058501bcd
Revises: 41bed6662f67
Create Date: 2025-01-22 23:36:58.502009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa058501bcd'
down_revision = '41bed6662f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('communications_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('communications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('communications_ibfk_1', 'logins', ['company_id'], ['id'])
        batch_op.create_foreign_key('communications_ibfk_2', 'logins', ['user_id'], ['id'])
        batch_op.drop_column('read')

    # ### end Alembic commands ###
