"""Your message describing the changes

Revision ID: 9243e73ad542
Revises: b8d5764de832
Create Date: 2025-04-03 19:45:09.543150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9243e73ad542'
down_revision = 'b8d5764de832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
