"""migration 26

Revision ID: 980b4e99fb0e
Revises: d53b5c485d91
Create Date: 2025-01-27 00:22:33.876366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '980b4e99fb0e'
down_revision = 'd53b5c485d91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('notifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['user_id'], ['login_id'])

    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.drop_constraint('resume_certifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'logins', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('resume_certifications_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notifications_ibfk_1', 'companies', ['user_id'], ['id'])

    # ### end Alembic commands ###
