"""migration 9

Revision ID: 991507a481c1
Revises: 84cd34d490a4
Create Date: 2025-01-13 06:14:38.584272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991507a481c1'
down_revision = '84cd34d490a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_vacancy', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('filled_vacancy', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('filled_vacancy')
        batch_op.drop_column('total_vacancy')

    # ### end Alembic commands ###
