"""o


Revision ID: a5f27436619e
Revises: d2fc5dd69481
Create Date: 2025-01-27 00:09:26.157873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f27436619e'
down_revision = 'd2fc5dd69481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_constraint('certifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'logins', ['user_id'], ['id'])

    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.drop_constraint('resume_certifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'logins', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('resume_certifications_ibfk_1', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('certifications_ibfk_1', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
