"""is_banned

Revision ID: a8e0a1e1c131
Revises: 7be6bdb4f345
Create Date: 2025-04-13 21:39:26.426684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e0a1e1c131'
down_revision = '7be6bdb4f345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
