"""Session token validation

Revision ID: ab9138e9b4bb
Revises: 37efff5e2ecc
Create Date: 2025-10-13 05:03:48.933505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9138e9b4bb'
down_revision = '37efff5e2ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['job_id'])

    with op.batch_alter_table('logins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', sa.Uuid(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logins', schema=None) as batch_op:
        batch_op.drop_column('session_token')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
