"""tskkskkllk

Revision ID: b2892ddbc5a5
Revises: 22594118131b
Create Date: 2025-04-01 03:06:40.238904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2892ddbc5a5'
down_revision = '22594118131b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.alter_column('date_applied',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('date_status_changed',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.alter_column('date_status_changed',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('date_applied',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
