"""favxuinijsxcs

Revision ID: c03ec2a0a528
Revises: 
Create Date: 2025-04-19 14:17:07.945449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03ec2a0a528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('year',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('couponuser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    with op.batch_alter_table('couponuser', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    with op.batch_alter_table('college', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
