"""Added Resume table to store user resumes and certifications

Revision ID: d0477b40ad71
Revises: 54524043101d
Create Date: 2024-12-31 13:59:47.506977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0477b40ad71'
down_revision = '54524043101d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.alter_column('resume_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.alter_column('resume_path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
