"""on

Revision ID: d2fc5dd69481
Revises: 7c0e5aaf31ad
Create Date: 2025-01-27 00:04:58.273986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2fc5dd69481'
down_revision = '7c0e5aaf31ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_constraint('certifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.drop_constraint('resume_certifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('resume_certifications_ibfk_1', 'logins', ['user_id'], ['id'])

    with op.batch_alter_table('certifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('certifications_ibfk_1', 'logins', ['user_id'], ['id'])

    # ### end Alembic commands ###
