"""migration 25

Revision ID: d53b5c485d91
Revises: 6204eff57efa
Create Date: 2025-01-27 00:03:08.650924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53b5c485d91'
down_revision = '6204eff57efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.drop_constraint('resume_certifications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_certifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('resume_certifications_ibfk_1', 'logins', ['user_id'], ['id'])

    # ### end Alembic commands ###
