"""migration 19

Revision ID: e32e52944ec1
Revises: 185c80dd0445
Create Date: 2025-01-18 22:12:17.445365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e32e52944ec1'
down_revision = '185c80dd0445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_constraint('communications_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('communications_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'logins', ['company_id'], ['id'])
        batch_op.create_foreign_key(None, 'logins', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('communications_ibfk_1', 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key('communications_ibfk_2', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
