"""IST Date change

Revision ID: e7116ab28a9e
Revises: c03ec2a0a528
Create Date: 2025-06-04 11:46:40.191457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7116ab28a9e'
down_revision = 'c03ec2a0a528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('salary',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('salary',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
